### ISSUE TITLE
Guidance on Configuring Datadog for AWS Secrets

### ISSUE THREAD

**Issue by jt24debug** [DataDog/datadog-secret-backend#16]
I followed all your steps up to step 6 completely without fail. After that 6th step, I created a file named "datadog-secret-backend.yaml" in the path "/etc/rapdev-datadog." Now, I need to define the path to call this file, "datadog-secret-backend.yaml."

Could you please share the next steps after step 7? I'm very confused about where to define the location of the "datadog-secret-backend.yaml" file either in "datadog.yaml" or in the path "/etc/datadog-agent/conf.d/mysql.d/conf.yaml."

Just for your information, I'm using an IAM Role to connect EC2 with Secrets Manager, not sharing any credentials. I’ve included both file contents and their locations. If you need any additional details, please let me know.

1)  datadog-secret-backend.yaml

Location:

backends:
  agent_secret:
    backend_type: aws.secrets
    secret_id: /datadog/dev/rds/db
    aws_session:
      aws_region: us-east-1
      aws_role_arn: arn:aws:iam::**:role/ec2-role
      
  2) conf.yaml

Location: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
  
  init_config:
  collect_settings: true
  logs_enabled: true

instances:
  - dbm: true
    host: ''
    port: 
    username: newone
    password: ENC[decrypt.sh]
    aws:
      instance_endpoint: ''

  - host: ''
    username: newonw
    password: 
    port: ''
    options:
      replication: false
      galera_cluster: true
      extra_status_metrics: true
      extra_innodb_metrics: true
      schema_size_metrics: false
      disable_innodb_metrics: false

**Comment by restump** [comment]
@jt24debug You'll need to set the `ENC[]` reference(s) in the Agent's `datadog.yaml` file to the use the backendId you created in the datadog-secret-backend configuration yaml. The format of the `ENC[]` reference for AWS Secrets Manager is defined [here](https://github.com/rapdev-io/datadog-secret-backend/blob/main/docs/aws/secrets.md#backend-configuration).

```yaml
# /etc/datadog-agent/datadog.yaml

api_key: "ENC[{backendId}:{secretKey}"
```

For example, based on the details you provided on this issue, the `ENC[]` reference would need to look like the following:

```yaml
# /etc/datadog-agent/conf.d/mysql.d/conf.yaml

instances:
  - host: ''
    username: newone
    password: ENC[agent_secret:db_password]
```

Also, currently the format of the AWS Secrets Manager secret `/datadog/dev/rds/db` value should be in JSON format: 

```json
{
  "db_password": "YourMySQLDBPassword"
}
```

In the future, we'll looking to support json path selection of the secret string for nested values, including just a simple string value. But currently it would need to be in a JSON format like the example above.

**Comment by jt24debug** [comment]
Thanks for some of the clarification but still i've few question regarding the same

1) Do I need to manually create the path for the file "datadog-secret-backend.yaml"? I’m unsure where this file should be placed. If the path needs to be created manually, could you also share the file and folder permissions, along with the user and group ownership? After that, how do I define that path in "datadog.yml"? Without defining the path, how will Datadog know which secret to use for MySQL?

backends:
  agent_secret:
    backend_type: aws.secrets
    secret_id: /datadog/dev/rds/db
  aws_session:
    aws_region: us-east-1
    aws_role_arn: arn:aws:iam::**:role/ec2-role


2) What should be the value of the following command that will be placed in datadog.yml? The backend ID will be "agent_secret", but what should the secret value be? Should it be "/datadog/dev/rds/db" or something else?


api_key: "ENC[{backendId}:{secretKey}"

**Comment by restump** [comment]
@jt24debug By default, the `datadog-secret-backend` command looks for the `datadog-secret-backend.yaml` file in the same directory. You can override this with the `-config /path/to/datadog-secret-backend.yaml`. If you want to specify a non-default location for the datadog-secret-backend.yaml configuration file, add the following to your /etc/datadog-agent/datadog.yaml configuration like so:

```yaml
secret_backend_command: /path/to/datadog-secret-backend
secret_backend_arguments: 
  - '-config /path/to/datadog-secret-backend.yaml'
  ```
  
The `datadog-secret-backend` is executed as your Datadog Agent user, usually `dd-agent` as a sub-process, so you'll want to configure the permissions on the `datadog-secret-backend` and `datadog-secret-backend.yaml` files as described by Datadog [here](https://docs.datadoghq.com/agent/configuration/secrets-management/?tab=linux#agent-security-requirements).
  
The AWS Secrets Manager secret will need to be in JSON format with a field you can access in the `ENC[]` of your Datadog Agent configuration file. Assuming you set your secret `/datadog/dev/rds/db` to the following JSON string:

```json
{
  "db_password": "YourMySQLDBPassword"
}
```

Then, you can access this secret anywhere in your `datadog.yaml` with the following `ENC[]` syntax:

```yaml
  password: ENC[agent_secret:db_password]
```

The `datadog-secret-backend` will parse the `ENC[]` references and lookup your AWS Secret Manager secret and connect as defined in the `datadog-secret-backend.yaml` file. In your example you created the `backendId` as `agent_secret`. The part of the string after the `:` is the `secretKey`, which in this case will need to be a JSON field name from the AWS Secrets Manager secret value: `db_password`. The field name is arbitrary, you can define is as you prefer, but it will need to case-sensitive match between the `ENC[]` reference and the actual field name in the AWS Secrets Manager secret value (JSON).

**Comment by heyysultan** [comment]
@restump @jt24debug Great conversation. I just need help with IAM role what kind of role it would be? can someone please share the json of a role through which DD agent can access to secrets?
I created a role but for EC2 to access secrets.

**Comment by heyysultan** [comment]
@restump 
I still get this error when I check the container logs;

> 2024-10-14 05:50:46 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:mysql | Error running check: [{"message": "(2003, \"Can't connect to MySQL server on 'ENC[webservices-secrets:DATABASE_HOST]' ([Errno -2] Name or service not known)\")", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/pymysql/connections.py\", line 613, in connect\n    sock = socket.create_connection(\n  File \"/opt/datadog-agent/embedded/lib/python3.8/socket.py\", line 787, in 

my datadog.yaml

```init_config:
instances:
  - dbm: true
    host: ENC[webservices-secrets:DATABASE_HOST]
    port: 3306
    username: datadog
    password: ENC[webservices-secrets:DATABASE_PASSWORD]
    database: ENC[webservices-secrets:DATABASE_NAME]
    tags:
      - 'env:staging'
    secret_backend_command:
```

my datadog-secret-backend.yaml

```
backends:
  webservices-secrets:
    backend_type: aws.secrets
    secret_id: lu-webservices-env
    aws_session:
      aws_region: us-west-1
      aws_role_arn: arn:aws:iam::xxxx:role/AWSSecretManagerAccessToDD
```

my container's configurations

```
datadog-agent:
    image: gcr.io/datadoghq/agent:7.36.1
    environment:
      - DD_API_KEY=${DATADOG_API_KEY} 
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .datadog/datadog.yaml:/etc/datadog-agent/conf.d/mysql.d/conf.yaml
```

**Comment by jt24debug** [comment]
@restump  I'm facing the following error, and I've provided all the files I used for reference. Please check and let me know if I've misconfigured any parameters or if something else is causing the issue, as the Datadog agent can't connect to MySQL using secrets.

Error logs :     raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'datadog'@'10.0.1.173' (using password: "********"
2024-10-14 05:59:02 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:71 in Error) | check:mysql | Error running check: [{"message":"(1045, \"Access denied for user 'datadog'@'10.0.1.173' (using password: "********"


1) datadog.yaml file 

secret_backend_command: /etc/rapdev-datadog/datadog-secret-backend
secret_backend_arguments:
  - '-config /etc/datadog-agent/datadog-secret-backend.yaml'

2) datadog-secret-backend.yaml

backends:
  agent_secret:
    backend_type: aws.secrets
    secret_id: /datadog/dev/rds/db
    aws_session:
      aws_region: us-west-1
      aws_role_arn: arn:aws:iam::*******:role/ec2-role


3) mysql.d/conf.yaml

location: /etc/datadog-agent/conf.d/mysql.d# cat conf.yaml

init_config:
  collect_settings: true
  logs_enabled: true

instances:
  - dbm: true
    host: 'dev-cluster-new.cluster-juoijjok85uj.us-west-1.rds.amazonaws.com'
    port: 4307
    username: datadog
    password: ENC[agent_secret:password]
    aws:
      instance_endpoint: 'dev-cluster-new.cluster-juoijjok85uj.us-west-1.rds.amazonaws.com


4) secret manager name : /datadog/dev/rds/db

Secret value 

password : ***

**Comment by heyysultan** [comment]
@jt24debug can you show me your container's configurations?

**Comment by jt24debug** [comment]
> @jt24debug can you show me your container's configurations?

@heyysultan We're not using any containers; we've currently configured APM with Datadog for RDS.

**Comment by heyysultan** [comment]
@jt24debug but to setup the agent dont you have to create a container for it? I have created one and through which I am trying to connect it. Can you share your infra with me how you are creating and configuring the agent? It would be very helpful for me.

**Comment by heyysultan** [comment]
@restump I have overviewed everything in the README file but I couldnt fine anything for datadog-agent as a container. Can you assure if rapdev is also for container or its only for agent installed on machine. Also I found out that there is no tar file for arm86, my machines are arm arch.

**Comment by jt24debug** [comment]
> @jt24debug but to setup the agent dont you have to create a container for it? I have created one and through which I am trying to connect it. Can you share your infra with me how you are creating and configuring the agent? It would be very helpful for me.

@heyysultan i've installed on daemon instead of on docker.

**Comment by restump** [comment]
> @restump I still get this error when I check the container logs;
> 
> > 2024-10-14 05:50:46 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:mysql | Error running check: [{"message": "(2003, "Can't connect to MySQL server on 'ENC[webservices-secrets:DATABASE_HOST]' ([Errno -2] Name or service not known)")", "traceback": "Traceback (most recent call last):\n  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/pymysql/connections.py", line 613, in connect\n    sock = socket.create_connection(\n  File "/opt/datadog-agent/embedded/lib/python3.8/socket.py", line 787, in
> 
> my datadog.yaml
> 
> ```
> instances:
>   - dbm: true
>     host: ENC[webservices-secrets:DATABASE_HOST]
>     port: 3306
>     username: datadog
>     password: ENC[webservices-secrets:DATABASE_PASSWORD]
>     database: ENC[webservices-secrets:DATABASE_NAME]
>     tags:
>       - 'env:staging'
>     secret_backend_command:
> ```
> 
> my datadog-secret-backend.yaml
> 
> ```
> backends:
>   webservices-secrets:
>     backend_type: aws.secrets
>     secret_id: lu-webservices-env
>     aws_session:
>       aws_region: us-west-1
>       aws_role_arn: arn:aws:iam::xxxx:role/AWSSecretManagerAccessToDD
> ```
> 
> my container's configurations
> 
> ```
> datadog-agent:
>     image: gcr.io/datadoghq/agent:7.36.1
>     environment:
>       - DD_API_KEY=${DATADOG_API_KEY} 
>       - DD_SITE=datadoghq.com
>       - DD_APM_ENABLED=true
>       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
>       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
>       - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
>     env_file: .env
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>       - .datadog/datadog.yaml:/etc/datadog-agent/conf.d/mysql.d/conf.yaml
> ```

@heyysultan For the containers, you need to specify the Datadog secrets backend command. For DaemonSets, it would be `DD_SECRET_BACKEND_COMMAND`. You'll also need to get the `datadog-secrets-backend` and `datadog-secrets-backend.yaml` files into your container image so it can be invoked. But reviewing your error message, it appears no attempt to decode your `ENC[]` references in the datadog configuration happened since you did not specify `DD_SECRET_BACKEND_COMMAND`.

**Comment by restump** [comment]
> @restump I have overviewed everything in the README file but I couldnt fine anything for datadog-agent as a container. Can you assure if rapdev is also for container or its only for agent installed on machine. Also I found out that there is no tar file for arm86, my machines are arm arch.

Unfortunately we did not cover that use case in our README and docs, but if you include the `datadog-secrets-backend` and `datadog-secrets-backend.yaml` files and then indicate the environment variable `DD_SECRET_BACKEND_COMMAND` pointing at the `datadog-secrets-backend` command, it should work. Let us know if hit any issues with that configuration.

**Comment by restump** [comment]
> @restump @jt24debug Great conversation. I just need help with IAM role what kind of role it would be? can someone please share the json of a role through which DD agent can access to secrets? I created a role but for EC2 to access secrets.

You'll need an IAM role with the following permissions (assuming the secret is in the same AWS account) -

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "arn:aws:iam::{YourAWSAccountID}:role/AWSSecretManagerAccessToDD"
        }
    ]
}
```

If you're using AWS ECS, then you can assign the task the IAM role. However, you'll need to create the right trust policy for the role assumption from the ECS task. See the following [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) from AWS.

**Comment by jt24debug** [comment]
@restump The IAM role defined in the datadog-secret-backend.yaml file has administrator access, and I can easily decrypt the database password using the AWS command. However, I am facing an issue when integrating AWS Secrets Manager with Datadog.

**Comment by restump** [comment]
> @restump The IAM role defined in the datadog-secret-backend.yaml file has administrator access, and I can easily decrypt the database password using the AWS command. However, I am facing an issue when integrating AWS Secrets Manager with Datadog.

We definitely don't recommend you use an administrator policy, particularly in production. We'd recommend you scope that down to just what's needed by the IAM role after testing.  

Could you test the `datadog-secret-backend` directly to see if there are any errors? If there are any errors, they will appear here.

```sh
# cd into the directory holding datadog-secret-backend command
echo '{"version: "1.0", "secrets": ["agent_secret:password"]}' | ./datadog-secret-backend 
# output should show the secret value or any errors
```

However, from your last comment, it appears to be decoding a password of some form, but it's not valid for the MySQL login. Is your secret value in AWS Secrets Manager the following json string:

```json
{
  "password": "YourPasswordSecret"
}
```

Finally, have you verified the MySQL user `datadog` and the password from the AWS Secrets Manager secret are valid?

**Comment by jt24debug** [comment]
@restump 
I updated the policy as per your recommendation, and when I ran the command mentioned above, it showed the complete password that I inserted in Secret Manager. I’ve attached a snapshot of all configurations for your review. Please check it and let me know, as I’m still facing the same error below. If I define the ENC in mysql.d/conf.yaml, do I need to define it again in datadog.yaml?


 raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'datadog'@'10.0.1.173' (using password: "********"
2024-10-15 06:02:33 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:71 in Error) | check:mysql | Error running check: [{"message":"(1045, \"Access denied for user 'datadog'@'10.0.1.173' (using password: "********"
2024-10-15 06:02:33 UTC | CORE | INFO | (pkg/collector/worker/check_logger.go:59 in CheckFinished) | check:mysql | Done running check
2024-10-15 06:02:35 UTC | CORE | INFO | (pkg/collector/worker/check_logger.go:40 in CheckStarted) | check:telemetry | Running check...
2024-10-15 06:02:35 UTC | CORE | INFO | (pkg/collector/worker/check_logger.go:59 in CheckFinished) | check:telemetry | Done running check




![secre-backend-1](https://github.com/user-attachments/assets/6823cbb8-26c0-4654-ad46-5774100d7793)


![secre-backend-2](https://github.com/user-attachments/assets/b0c6c522-1d4a-4e45-8645-d27d854f9793)


![secre-backend-3](https://github.com/user-attachments/assets/b93d7b4f-939b-449e-bfc0-313866f33571)

**Comment by restump** [comment]
If the echo command worked, then everything is working with permissions. The echo command is essentially what Datadog does when it calls the secrets command. Datadog, at agent start-up, will parse all your datadog configuration yaml files looking for `ENC[]`. It will then send all these `ENC[]` references into the secrets command and replace all instances of `ENC[]` with the appropriate secret value.

You don't need to use `ENC[agent_secret:password]` again the datadog.yaml file, only use it when you want that password to actually be replaced. In this case, for the dbm instance password.

Are you able to connect to your mysql rds instance `dev-cluster-new.cluster-juoijjok85uj.us-west-1.rds.amazonaws.com` with the user `datadog` and the `password` secret value manually? 

We would expect the `ENC[]` replacement to happen without string quotes in the yaml, but may want to also quote it just in case like the following in the `mysql.d/conf.yaml` file:

```yaml
init_config:
  collect_settings: true
  logs_enabled: true

instances:
  - dbm: true
     host: 'dev-cluster-new.cluster-juoijjok85uj.us-west-1.rds.amazonaws.com'
     port: 4307
     username: datadog
     password: 'ENC[agent_secret:password]'
     
     aws:
       instance_endpoint: 'dev-cluster-new.cluster-juoijjok85uj.us-west-1.rds.amazonaws.com'
```

**Comment by jt24debug** [comment]
@restump I appreciate your help, and I’m happy to report that the issue has been successfully resolved.
